/**
 * Browser-side reply extraction script for single post pages.
 * Injected into page.evaluate() on post detail pages.
 */

export function getReplyExtractScript(maxReplies: number): string {
    return '(() => {\n'
        + '    const replies = [];\n'
        + '    const containers = document.querySelectorAll(\'[data-pressable-container="true"], div[role="article"], article\');\n'
        + '\n'
        + '    const replyContainers = Array.from(containers).slice(1);\n'
        + '\n'
        + '    const parseCount = (raw) => {\n'
        + '        if (!raw) return 0;\n'
        + '        const cleaned = raw.replace(/,/g, \'\');\n'
        + '        const kMatch = cleaned.match(/^([\\\\d.]+)K$/i);\n'
        + '        if (kMatch) return Math.round(parseFloat(kMatch[1]) * 1000);\n'
        + '        const mMatch = cleaned.match(/^([\\\\d.]+)M$/i);\n'
        + '        if (mMatch) return Math.round(parseFloat(mMatch[1]) * 1000000);\n'
        + '        return parseInt(cleaned, 10) || 0;\n'
        + '    };\n'
        + '\n'
        + '    for (const el of replyContainers) {\n'
        + '        if (replies.length >= ' + maxReplies + ') break;\n'
        + '\n'
        + '        const textContent = (el.textContent || \'\').trim();\n'
        + '        if (textContent.length < 5) continue;\n'
        + '\n'
        + '        const authorLink = el.querySelector(\'a[href^="/@"]\');\n'
        + '        let author = \'unknown\';\n'
        + '        if (authorLink) {\n'
        + '            const linkText = (authorLink.textContent || \'\').trim();\n'
        + '            if (linkText) {\n'
        + '                author = linkText;\n'
        + '            } else if (authorLink.href) {\n'
        + '                const m = authorLink.href.match(/@([^/?]+)/);\n'
        + '                if (m) author = m[1];\n'
        + '            }\n'
        + '        }\n'
        + '\n'
        + '        const timeEl = el.querySelector(\'time\');\n'
        + '        const publishedAt = timeEl ? (timeEl.textContent || \'\').trim() : \'\';\n'
        + '\n'
        + '        const spans = el.querySelectorAll(\'span\');\n'
        + '        let content = \'\';\n'
        + '        for (const s of spans) {\n'
        + '            const t = (s.textContent || \'\').trim();\n'
        + '            if (t.length > 10 && t !== author && !/^\\\\d+[hmd]$/.test(t)) {\n'
        + '                content = t;\n'
        + '                break;\n'
        + '            }\n'
        + '        }\n'
        + '\n'
        + '        if (!content) {\n'
        + '            content = textContent.slice(0, 500);\n'
        + '        }\n'
        + '\n'
        + '        let likeCount = 0;\n'
        + '        const buttons = el.querySelectorAll(\'[role="button"]\');\n'
        + '        for (const btn of buttons) {\n'
        + '            const btnText = (btn.textContent || \'\').trim();\n'
        + '            const countMatch = btnText.match(/^Like([\\\\d.,]+[KkMm]?)$/);\n'
        + '            if (countMatch) {\n'
        + '                likeCount = parseCount(countMatch[1]);\n'
        + '                break;\n'
        + '            }\n'
        + '        }\n'
        + '\n'
        + '        replies.push({ author, content, publishedAt, likeCount });\n'
        + '    }\n'
        + '\n'
        + '    return replies;\n'
        + '})()';
}
